# Nixpacks configuration to override detected system packages
# Ensures psycopg2 can compile against libpq without using the non-existent postgresql_16.dev

[phases.setup]
# Pin exact nix packages available in nixpkgs
nixPkgs = [
  "python39",
  "postgresql_16",
  "gcc",
  "pkg-config"
]
