services:
  - type: web
    name: mohandb
    env: python
    plan: free
    buildCommand: |
      pip install --upgrade pip
      pip install wheel
      pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.9
      - key: SECRET_KEY
        generateValue: true
    autoDeploy: true
